// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddTasbeeh: typeof import('./src/components/AddTasbeeh.vue')['default']
    CreateTasbeehSchedule: typeof import('./src/components/CreateTasbeehSchedule.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LonelyWolf: typeof import('./src/components/LonelyWolf.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    OptionPage: typeof import('./src/components/OptionPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabNavbar: typeof import('./src/components/nav/TabNavbar.vue')['default']
    TasbeehCard: typeof import('./src/components/cards/TasbeehCard.vue')['default']
    TasbeehList: typeof import('./src/components/TasbeehList.vue')['default']
    TasbeehListPage: typeof import('./src/components/TasbeehListPage.vue')['default']
    TasbeehTahleel: typeof import('./src/components/TasbeehTahleel.vue')['default']
  }
}
