/**
 * Shared Rooms — backend contract (the port).
 *
 * This module defines EVERYTHING the rest of the app knows about the sync
 * backend: the callable surface, the payload shapes, and the error taxonomy.
 * It must never import a concrete backend (Supabase or otherwise).
 *
 * Swapping backends = implementing `SharedRoomBackend` and returning it from
 * the factory in ./index.ts. `MockSharedRoomBackend` is the reference "dumb
 * testing class"; `SupabaseSharedRoomBackend` is the production adapter.
 * See docs/SharedGoals-Design.md
 */

// ---------- Error taxonomy ----------

export type SharedRoomErrorCode =
  | 'not-configured'
  | 'not-authenticated'
  | 'network'
  | 'room-not-found'
  | 'room-closed'
  | 'room-full'
  | 'window-not-started'
  | 'window-ended'
  | 'not-a-member'
  | 'not-owner'
  | 'invalid-delta'
  | 'invalid-input'
  | 'unknown';

export class SharedRoomError extends Error {
  readonly code: SharedRoomErrorCode;
  /** Permanent errors will never succeed on retry — dropped from the outbox. */
  readonly permanent: boolean;

  constructor(code: SharedRoomErrorCode, message?: string) {
    super(message || code);
    this.name = 'SharedRoomError';
    this.code = code;
    this.permanent = !['network', 'unknown', 'not-authenticated'].includes(code);
  }
}

// ---------- Payload shapes (transport-agnostic; dates as ISO strings) ----------

export interface RoomSummary {
  id: string;
  code: string;
  title: string;
  zikrName: string;
  zikrArabic: string | null;
  target: number;
  total: number;
  startsAt: string;
  endsAt: string;
  ownerId: string;
  status: 'active' | 'closed';
}

export interface RoomMemberPayload {
  name: string;
  joinedAt: string;
  /** Server-side uid — needed for owner removal; carries no contribution data. */
  userId?: string;
}

export interface RoomStatePayload {
  room: RoomSummary;
  members: RoomMemberPayload[];
  isMember: boolean;
}

export interface CreateRoomInput {
  title: string;
  zikrName: string;
  zikrArabic?: string;
  target: number;
  startsAt: Date;
  endsAt: Date;
  displayName: string;
}

// ---------- The port ----------

export interface SharedRoomBackend {
  /** Human-readable backend name (diagnostics). */
  readonly name: string;

  /** Whether the backend has everything it needs to operate. */
  isConfigured(): boolean;

  /** Ensure a stable no-login identity for this device; returns its uid. */
  ensureUserId(): Promise<string>;

  createRoom(input: CreateRoomInput): Promise<RoomStatePayload>;
  joinRoom(code: string, displayName: string): Promise<RoomStatePayload>;

  /**
   * Apply an atomic, idempotent increment. `eventId` is generated by the
   * client; backends MUST dedupe on it (retries are expected).
   */
  contribute(code: string, delta: number, eventId: string): Promise<{ total: number }>;

  getRoomState(code: string): Promise<RoomStatePayload>;
  removeMember(code: string, userId: string): Promise<void>;
  leaveRoom(code: string): Promise<void>;
  closeRoom(code: string): Promise<void>;
}
